#!/bin/bash

set -e

VOID_SRCPKGS="$HOME/void-packages/srcpkgs"
PKG_NAME=$(basename "$1")

if [ "$#" -ne 1 ]; then
	echo "Usage: cppkg [srcpkgs/<package>]"
	exit 0
fi

if [ ! -e "$1" ]; then
	echo "Error: File or directory does not exist: $1"
	exit 1
fi

if [ -z $VOID_SRCPKGS ]; then
	echo "Error: VOID_SRCPKGS not specified."
	exit 2
fi

cp -rv "$1" "$VOID_SRCPKGS/$PKG_NAME"
